### ISSUE TITLE
Persistence storage with CSI driver and AWS EFS

### ISSUE THREAD

**Issue by wcarlsen** [dfds/infrastructure-modules#64]

**Comment by wcarlsen** [comment]
The CSI driver in combination with AWS EFS solves the issue that AWS EBS has with being hard coupled to AZ at the prize of higher cost and no dynamic provisioning.

**Comment by wcarlsen** [comment]
https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html

**Comment by wcarlsen** [comment]
Requirement 1.14 of AWS EKS.

**Comment by wiredworm** [comment]
I had a chat with Willi and it makes sense now.  Right now we run the CSI Drive for EBS Volumes which means the developers can in theory provision persistent volumes using EBS.  The problem with this is that these volumes are AZ bound so we don't have any sort of fault tolerance on the data; if we lose an AZ then the data is gone.

The CSI Driver for EFS should, in theory, allow developers to provision EFS-volumes which are not AZ constrained. 

Off the back of this I need to do some more research.  Some of the CSI stuff is now offered as an EKS-Addon so it might be one approach, or the other alternative is that I start by trying a manual install of the EFS CSI Driver in my sandbox and see how it looks to actually provision and work with EFS-backed volumes.

**Comment by wiredworm** [comment]
The work around this is now done, but the implementation differs from that used by the AWS CSI Driver for EBS so i've written some notes below to give a bit of explanation around the differences.

**AWS CSI Driver for EBS**

The AWS CSI Driver for EBS is built in such a way that anyone can provision an EBS volume by simply defining a Persistent Volume Claim using a YAML manifest like this:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-disk
spec:
  storageClassName: csi-gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

When such a manifest is applied the driver will automatically ensure that a suitable EBS volume is provisioned.


**AWS CSI Driver for EFS**

The AWS CSI Driver for EFS does not provide a means for an individual to provision an Elastic File System via YAML manifests.  Instead they have to be defined in Terraform and once created a Kubernetes Storage Class will also be defined which links to the file system.  Those wishing to use the EFS volume can then do so by referencing the appropriate storage class as shown in the sample below.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-efs-test-volume-1
  resources:
    requests:
      storage: 5Gi
``` 


** Installing the new AWS CSI Driver for EFS **

1. Increment the reference to infrastructure-modules in both the Service and Cluster phase to **version** or later.  Executing an apply of the cluster phase and the service phase at this point would cause the CSI Driver for EFS to be deployed.  By default the latest version of the Helm Chart will be used unless a specific version is provided in the variable efs_csi_driver_chart_version.
2. It is recommended that before applying the two phases you add a section of code similar to this in the HCL file for the Services phase.  Please note that you may need to increment the version if later releases have subsequently been made available:

```
  # --------------------------------------------------
  # AWS EFS CSI Driver
  # --------------------------------------------------

  efs_csi_driver_chart_version = "2.2.2"
```

3. Once the code is updated then apply both the cluster and services phase.  This is necessary because there is a small change made to one of the IAM Roles which is provisioned during the cluster phase.  Failing to make this change will prevent pods from being attached to their requested file systems.

4. The k8s-services portion of infrastructure-modules also includes a module reference which will create an EFS File System named 'volume-1'.  This will automatically result in a storage class called csi-efs-volume-1 being created.  Users of the cluster can then make use of this storage using a YAML manifest as shown below.

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-efs-volume-1
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app-1
spec:
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /data/out; sleep 5; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-claim-1
```
